# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33591e2884efb12d6b7c4e5c74e1a58fea12073532dfdcc1156d3faf7c641ff2148a6783fba5d63179f437e7ee0b580ee1232117563543b74d8503a93edfd0db

test:
  secret_key_base: eac0eb325bd720cdf618300e4a4af239034b8c07c39ed90671ca4180822e7f3f14a5f2540cb1de385aaecf073e95c2dd775624539836a92bf8dc83283fb9d10f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
